#!/usr/bin/env python3

# Given: A DNA string s of length at most 1000 bp.
#
# Return: Four integers (separated by spaces) representing 
# the respective number of times that the symbols 'A', 'C', 'G', and 'T' 
# occur in s

# This method gets the count of
# items n in the string 
def GetCount(string, n):

    # set count to 0
    count = 0
    
    # loop through the string
    for i in string:
    
        # if the current char is same as n
        if i == n:
        
            # increment count
            count += 1
        
    return count
 
# DNA string
DNA = "AATGCCATAGCTTTTGGGGTGAGTGTATGGGGGGGGCAAATGTAGCGAGACTAGACGCAGGCACTATCTGTTCCTGTGTTGGTAAAATGCGCACCGGCGCGCATGCTTACTGAGCGCAAAACTAATTCGCCGCAGTGGTACCCCTGAGGTTCATCGTGTGAGCTGTAGGCATTGACGGAGCCTATTTCGGTCTCTTGGGAAAACGGACTCTTGAGTGAATAGGCCCCCTGTCTTGGAAGTGGATGCTCTTCGGGTTACGCAGTTAAAGAGATCGCCCCTGGAGGTGTGTATGCGACGGAACGCCGCAACAGCGTGGACGGCGGGGTTGGTATGTGTGGAGTCTGCGTTGCAAGAGCTATCTTTATCACGGGCAAAATTGACTCTCTGAAAGTTGGAAAAGAATCTGACCGCAAATAGGCGTAATTTTTGTGACAAACTAGACCCCCTTCGAAAGCCTGCATGATATTCTTCAACCTGACCATGGATGCAAACTTGGTTCAAGCAGGGCGTACTACTGAGGGAGCGCCCCGATGGGCATCCCCGCATATGTGCTCGGTCTTGTCCATCGCTCTCGGGCGCAAGACTTGCCAAGGAGCACCTCCCAAGCCATTCCTGAGAGGTACCATGTTTCGTTAAGAACGAAAATAGACGCCACTTGTGTTCTAGGACTGAGAAGGGTTGTACACTGAGAGAGACCTCAAGTGGACCATAAAACGATCAAGCCATAATCAATGTTCCATGGGGTAAGGGATAACCTCCCGTAAGGAGAGCACGCGACTTTAGTTCCTGTCGATAATTCAATAACCAGTTCGCACTGACCGCTCTTCTAGATAACGTATCAGTCGAGATCTTCCCCAGGCTTTCAATGCATACAATGAGTGGATCAATAAACCAATAATCCGTTCTGCGGTTTAGATT"

# get the count of each nucleotide
A = GetCount(DNA, 'A')
C = GetCount(DNA, 'C')
G = GetCount(DNA, 'G')
T = GetCount(DNA, 'T')

# print out the count of each nucleotides
print("%d %d %d %d" % (A,C,G,T))
